apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-1
  namespace: default
spec:
  # serviceName: kafka1
  replicas: 1
  selector:
    matchLabels:
      name: kafka-broker-1
  template:
    metadata:
      labels:
        app: kafka-broker-1
    spec:
      nodeSelector:
        servertype: analytics
      containers:
      - name: kafka
        image: wurstmeister/kafka
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "load-balancer URL"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181,zoo3:2181
        - name: KAFKA_CREATE_TOPICS
          value: "test-topic:3:2:compact"
        - name: KAFKA_LOG_DIRS
          value: /kafka/kafka-logs
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_JMX_PORT
          value: "5555"
        - name: KAFKA_CLEANUP_POLICY
          value: "compact"
        # volumeMounts:
        #   - name: xr-volume
        #     mountPath: "/kafka/kafka-logs"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
  namespace: default
  labels:
    app: kafka-broker-1
spec:
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka-broker-1
  type: LoadBalancer